import type { Metadata } from "next";
import { Geist, Geist_Mono, Darumadrop_One} from "next/font/google";
import "./globals.css";

const darumadropOne = Darumadrop_One({
  variable: "--font-darumadrop-one",
  subsets: ["latin"],
  weight: "400"
});

export const metadata: Metadata = {
  title: "All About Peeranut",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${darumadropOne.className} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
